version: '3.8'

services:

  maturity-app:

    build: .

    image: priyabratakhandual/maturity:latest

    container_name: maturity

    restart: always

    ports:
      - "7000:7000"

    environment:
      PORT: 7000